/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:5767ac3a-64c4-455e-b009-e1832cd77b50",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_m8PXzMpfq",
    "aws_user_pools_web_client_id": "9irl4bsuu4j5h6doefrnpg064",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://i5ujrjzk3za5flaitscasgvnvq.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-glxlbvoih5efdca3xjgqhptd5q",
    "aws_user_files_s3_bucket": "awsd0eca2602be04debbe723318e36faa0664648-staging",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
